project:
  type: website
  output-dir: docs

website:
  title: "SI Ocean DNA"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Best Practices"
        contents:
        - qmd/bestpractices.qmd
      - section: "Data Management"
        contents:
        - qmd/datamanagement.qmd
      - section: "Utility Scripts"
        contents: 
        - qmd/utilityscripts/batchRenameFiles.qmd
        - qmd/utilityscripts/recursiveReplaceStrings.qmd
      - section: "Hydra Analysis Scripts"
        contents:
        - qmd/hydrascripts.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    mermaid:
      theme: default



