project:
  type: website
  output-dir: docs

website:
  title: "SI Ocean DNA"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "Best Practices"
        contents:
        - qmd/bestpractices.qmd
      - section: "Data Management"
        contents:
        - qmd/datamanagement.qmd
      - section: "Data Management Scripts"
        contents:
        - qmd/dataManagementScripts/DNA_QC.qmd
        - qmd/dataManagementScripts/raw_sequence_validate.qmd
      - section: "Utility Scripts"
        contents: 
        - qmd/utilityScripts/validate_biosample_taxonomy.qmd
        - qmd/utilityScripts/batchRenameFiles.qmd
        - qmd/utilityScripts/recursiveReplaceStrings.qmd
      - section: "Hydra Analysis Scripts"
        contents:
        - qmd/hydraScripts/BLAST_18s_28s.qmd
        - qmd/hydraScripts/GetOrganelle.qmd
        - qmd/hydraScripts/Go_fetch.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    mermaid:
      theme: default



