project:
  type: website
  output-dir: docs

website:
  title: "SI Ocean DNA"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Best Practices"
        contents:
        - qmd/bestpractices.qmd
      - section: "Data Management"
        contents:
        - qmd/datamanagement.qmd
      - section: "Utility Scripts"
        contents: 
        - qmd/utilityscripts.qmd
      - section: "Hydra Analysis Scripts"
        contents:
        - qmd/hydrascripts.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true



