---
title: "Smithsonian National Museum of Natural History Ocean DNA"
---

Welcome to the Smithsonian NMNH Ocean DNA computational resources website. Here you will find data management guides, analytical workflows, and helpful utility scripts.

## What is Ocean DNA?

[Ocean DNA](https://naturalhistory.si.edu/initiatives/oceans/ocean-science-center/ocean-dna) is a coordinated effort across the [Smithsonian National Museum of Natural History](https://naturalhistory.si.edu/) to leverage our collections and adopt museum practices to support the use of DNA sequencing to survey marine life and assess ocean health. We place a special emphasis on undiscovered “dark taxa" that may play a critical role in ecosystems.

Ocean DNA will develop trusted genetic reference libraries to serve emerging sequence-based biodiversity technologies, unlocking the full potential of environmental DNA. Ocean DNA will improve genetic-based surveys of marine life to inform policy, conservation, and the sustainable use of marine resources. 

We will use our existing collections, implement field expeditions, build on our genomic expertise, and leverage our partnerships. Ocean DNA will discover new species, detect invasive species, monitor ocean health, measure change, assess management practices, and inform conservation for life on a sustainable planet.
